[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
bytes = "1.5"
rand = "0.8"
tempfile = "3.8"
tokio = { version = "1.32", features = ["fs", "rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1", features = ["io-util"] }
